version: "3"
services:
  backend:
    restart: always
    build: backend/
    environment:
      - MONGO_URL=mongodb://mongo:27017/
      - PORT=3000
    ports:
      - "3000:3000"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
